title: La programmation robotique pour tous
author: Louis-Daniel SAZGOT
email: sagotdaniel@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Ceci est ma description.

# social links
#twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  LDSrobotique # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
