title: LDSrobotique
author: Louis*Daniel SAGOT
email: danielsagot@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Description de ma page.

# social links
#twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  LDSrobotique # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
